services:
  ollama:
    container_name: ollama
    image: ollama/ollama
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ "gpu" ]
              count: 1 # Adjust count for the number of GPUs you want to use
    ports:
      - "11434:11434"
    volumes:
      - ./ollama:/root/.ollama
