services:
  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    container_name: qdrant
    ports:
      - 6333:6333
      - 6334:6334
    expose:
      - 6333
      - 6334
      - 6335
    configs:
      - source: qdrant_config
        target: /qdrant/config/production.yaml
    volumes:
      - ./qdrant_data:/qdrant/storage
    networks:
      - my-network

  ollama:
    container_name: ollama
    image: ollama/ollama
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ "gpu" ]
              count: 1 # Adjust count for the number of GPUs you want to use
    ports:
      - "11434:11434"
    expose:
      - 11434
    volumes:
      - ./ollama:/root/.ollama
    networks:
      - my-network

  app:
    build: .
    depends_on:
      - qdrant
      - ollama
    ports:
      - "420:420"
    expose:
      - 420
    environment:
      - OLLAMA_HOST=http://ollama:11434
      - LANGCHAIN_TRACING_V2="true"
      - LANGCHAIN_PROJECT="repo-rover"
      - LANGCHAIN_ENDPOINT="https://api.smith.langchain.com"
    volumes:
      - .:/app
      - /app/.venv
    secrets:
      - qdrant_api_key
      - nomic_api_key
      - github_repo
      - openai_api_key
      - langchain_api_key
      - github_app_id
      - github_app_private_key
      - github_pat
    deploy:
      resources:
        limits:
          cpus: '8'
        reservations:
          cpus: '8'
    restart: on-failure
    stdin_open: true
    tty: true
    networks:
      - my-network

configs:
  qdrant_config:
    content: |
      log_level: INFO

networks:
  my-network:


secrets:
  qdrant_api_key:
    file: secrets/qdrant_api_key.txt
  openai_api_key:
    file: secrets/openai_api_key.txt
  langchain_api_key:
    file: secrets/langchain_api_key.txt
  github_app_id:
    file: secrets/github_app_id.txt
  github_app_private_key:
    file: secrets/github_app_private_key.pem
  github_pat:
    file: secrets/github_pat.txt
  nomic_api_key:
    file: secrets/nomic_api_key.txt
  github_repo:
    file: secrets/github_repo.txt
